spring:
  datasource:
    url: jdbc:mariadb://localhost:3381/accountapi
    driver-class-name: org.mariadb.jdbc.Driver
    username: accountuser
    password: accountpassword

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect